### ISSUE TITLE
Add shell-lint to the CI for the shell scripts

### ISSUE THREAD

**Issue by neelanjan00** [iptables-viz/iptables-viz#18]
Add shell-lint to the CI for the shell scripts

**Comment by AlexNDRmac** [comment]
Hi, I can help with it.

**Comment by neelanjan00** [comment]
> Hi, I can help with it.

Please feel free to implement it! Here's the GitHub action: https://github.com/marketplace/actions/shell-linter
You'd have to scan only the [scripts](https://github.com/iptables-viz/iptables-viz/tree/main/scripts) dir.

**Comment by AlexNDRmac** [comment]
@neelanjan00 I saw that you using 4 separate workflows for build and push.
I can rework it as single workflow to avoid code duplications. It might looks like:
- lint workflow (starts always)
- build and push workflow (starts only when lint was successful)

build and push workflow will always build back and front (only for PR) and push these images only for push event on main branch.

What do you think about it?

**Comment by neelanjan00** [comment]
> @neelanjan00 I saw that you using 4 separate workflows for build and push.
> I can rework it as single workflow to avoid code duplications. It might looks like:
> - lint workflow (starts always)
> - build and push workflow (starts only when lint was successful)
> 
> build and push workflow will always build back and front (only for PR) and push these images only for push event on main branch.
> 
> What do you think about it?

I think separately executing frontend and backend actions for the respective changes is better than running both of them always, as it will save execution time, resources and will scale well. If you think that we can reduce the duplication while retaining separate execution then it'd be great.

Also, can you explain the approach for using a single action for both PR checks (build) and push to main (build + push)?

**Comment by AlexNDRmac** [comment]
Single action - means, you'll have one workflow for push and PR, decision about build/build+push will be performed by github event.

It might looks like this

```yaml
    - name: Push image only for main branch
       id: detect-push
       run: |
           if [ "${{ github.event_name }}" = "push"  ]; then
              echo "main=true" >> $GITHUB_OUTPUT
           else
              echo "main=false" >> $GITHUB_OUTPUT
           fi

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        platforms: linux/amd64,linux/arm64
        push: ${{ steps.detect-push.outputs.main }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/iptables-viz-backend:latest

```

About separate builds for front/back - I mean parallel builds for front and back after lint action. So, linters always starts first, then if linters pass without errors - in parallel starts builds for front and back. Action about push after build will be handled by step with simple checks, like in example above.
